### ISSUE TITLE
hloc integration?

### ISSUE THREAD

**Issue by catid** [Parskatt/DeDoDe#11]
Any plans or suggestions for how to integrate this into hloc?

**Comment by Parskatt** [comment]
Not right now, no. From what I remember its quite simple to do though so maybe if requested a lot.

**Comment by Vincentqyw** [comment]
> Any plans or suggestions for how to integrate this into hloc?

image maching webui have already done this work, [here](https://github.com/Vincentqyw/image-matching-webui/blob/main/hloc/extractors/dedode.py) is a simple wrapper function, you can easily integrate into hloc.

**Comment by ghoshaw** [comment]
@catid , Does Dedode perform better than superpoint+superglue in hloc+Aachen?

**Comment by catid** [comment]
No I wasn't able to improve on SPSG but also I'm not an expert in this stuff.  Here's my code if you want to build on: https://github.com/catid/hloc

**Comment by ghoshaw** [comment]
ok, thanks
