### ISSUE TITLE
"W" not in this function

### ISSUE THREAD

**Issue by gersonsolaris** [Parskatt/DeDoDe#19]
https://github.com/Parskatt/DeDoDe/blob/457193690c387b65e17a2035fcfc66cfa0515e08/DeDoDe/datasets/megadepth.py#L174C1-L175C55

**Comment by Parskatt** [comment]
What is W?

**Comment by gersonsolaris** [comment]
> What is W?

![image](https://github.com/Parskatt/DeDoDe/assets/139833567/0f0afaa3-f809-4de8-9239-27253e469093)

**Comment by Parskatt** [comment]
Aha, should be W_A / W_B respectively.

**Comment by gersonsolaris** [comment]
> Aha, should be W_A, W_B respectively. Must have copied wrongly from somewhere.

thx, this issue is resolved. 😃
