### ISSUE TITLE
run demo_match.py ​​but don't get any matches

### ISSUE THREAD

**Issue by GhYang0519** [Parskatt/DeDoDe#21]
![image](https://github.com/Parskatt/DeDoDe/assets/93421835/7091280f-2f2d-4151-9957-3f616e116887)
![image](https://github.com/Parskatt/DeDoDe/assets/93421835/fb9c8755-827c-4d06-ab61-a027dcd6d178)
Hope you can help me, thank you.

**Comment by GhYang0519** [comment]
BTW, my python version is 3.8.10. I deleted the type hints that are only supported by the new version. The code can run without any errors, but I don’t get any matches. When I run demo_kpts.py, I don’t get any. keypoints

**Comment by Parskatt** [comment]
It seems all your descriptions are nans, can you show the picture you sent in?

**Comment by GhYang0519** [comment]
yeah, I am using the example image.

**Comment by Parskatt** [comment]
That's very strange. When I get some time I'll have a check, but haven't seen that issue before.

**Comment by GhYang0519** [comment]
Okay, waiting for your good news.

**Comment by GhYang0519** [comment]
Hey! I've noticed that when I run the model and data on the CPU, there are no occurrences of data being NaN. I haven't conducted a detailed analysis yet to understand the specific reasons for this. With this information, perhaps you could speculate on the key issue.

**Comment by GhYang0519** [comment]
Additionally, I have a question: I have multiple images of an object from different perspectives, and I obtain descriptors for each of them using DeDoDe, then concatenate them to form my template. During inference, I'm wondering if DeDoDe can still perform well when faced with this concatenated descriptor. Does the matching score still hold significance at this point? In other words, can it still identify descriptors and keypoints within this stack of descriptors that best match the current input image?
Or do you have any better suggestions? I really hope you can help me! Thank you very much.

**Comment by Parskatt** [comment]
> Hey! I've noticed that when I run the model and data on the CPU, there are no occurrences of data being NaN. I haven't conducted a detailed analysis yet to understand the specific reasons for this. With this information, perhaps you could speculate on the key issue.

We run on float16, it could be some overflow or underflow in your case, but haven't seen it myself. What gpu and cuda?

**Comment by Parskatt** [comment]
> Additionally, I have a question: I have multiple images of an object from different perspectives, and I obtain descriptors for each of them using DeDoDe, then concatenate them to form my template. During inference, I'm wondering if DeDoDe can still perform well when faced with this concatenated descriptor. Does the matching score still hold significance at this point? In other words, can it still identify descriptors and keypoints within this stack of descriptors that best match the current input image?
> Or do you have any better suggestions? I really hope you can help me! Thank you very much.

Do you mean to identify which viewpoint is most similar to current viewpoint? Dedode is not invariant, so I think it should work, but not sure if I exactly got what you mean.

**Comment by GhYang0519** [comment]
Well, it’s a very poor GPU : Nvidia T1200  CUDA version 11.4

**Comment by Parskatt** [comment]
> Well, it’s a very poor GPU : Nvidia T1200  CUDA version 11.4    

What I would do is run with a debugger and find where the first nan shows up in the model forward. Perhaps pytorch has some flag to raise error when this happens?

**Comment by GhYang0519** [comment]
> > Additionally, I have a question: I have multiple images of an object from different perspectives, and I obtain descriptors for each of them using DeDoDe, then concatenate them to form my template. During inference, I'm wondering if DeDoDe can still perform well when faced with this concatenated descriptor. Does the matching score still hold significance at this point? In other words, can it still identify descriptors and keypoints within this stack of descriptors that best match the current input image?
> > Or do you have any better suggestions? I really hope you can help me! Thank you very much.
> 
> Do you mean to identify which viewpoint is most similar to current viewpoint? Dedode is not invariant, so I think it should work, but not sure if I exactly got what you mean.

My requirement is to estimate the pose information of a target object through RGB images using the PnP method. I will prepare approximately ten images taken from different angles, for which I already know the object's pose information. Using DeDoDe, I will extract descriptors from these ten images and establish 2D-3D correspondences, then concatenate them. For a new image, I will extract descriptors and match them with the concatenated template. This process allows me to establish the 2D-3D relationship between the input and template images, enabling the use of PnP to solve for pose information.

**Comment by Parskatt** [comment]
> > > Additionally, I have a question: I have multiple images of an object from different perspectives, and I obtain descriptors for each of them using DeDoDe, then concatenate them to form my template. During inference, I'm wondering if DeDoDe can still perform well when faced with this concatenated descriptor. Does the matching score still hold significance at this point? In other words, can it still identify descriptors and keypoints within this stack of descriptors that best match the current input image?
> > > Or do you have any better suggestions? I really hope you can help me! Thank you very much.
> > 
> > Do you mean to identify which viewpoint is most similar to current viewpoint? Dedode is not invariant, so I think it should work, but not sure if I exactly got what you mean.
> 
> My requirement is to estimate the pose information of a target object through RGB images using the PnP method. I will prepare approximately ten images taken from different angles, for which I already know the object's pose information. Using DeDoDe, I will extract descriptors from these ten images and establish 2D-3D correspondences, then concatenate them. For a new image, I will extract descriptors and match them with the concatenated template. This process allows me to establish the 2D-3D relationship between the input and template images, enabling the use of PnP to solve for pose information.

Yes that should work.

**Comment by GhYang0519** [comment]
> > Well, it’s a very poor GPU : Nvidia T1200  CUDA version 11.4
> 
> What I would do is run with a debugger and find where the first nan shows up in the model forward. Perhaps pytorch has some flag to raise error when this happens?

I tried using torch.autograd.set_detect_anomaly(True), but it didn't take effect.
![image](https:github.com/Parskatt/DeDoDe/assets/93421835/f7625303-d9a7-4aba-9da6-2ecdde0c205b)
Here, features will change to nan
![image](https://github.com/Parskatt/DeDoDe/assets/93421835/31b87785-9017-4cf7-bfc4-e9af1c8219e8)

**Comment by GhYang0519** [comment]
> > > > Additionally, I have a question: I have multiple images of an object from different perspectives, and I obtain descriptors for each of them using DeDoDe, then concatenate them to form my template. During inference, I'm wondering if DeDoDe can still perform well when faced with this concatenated descriptor. Does the matching score still hold significance at this point? In other words, can it still identify descriptors and keypoints within this stack of descriptors that best match the current input image?
> > > > Or do you have any better suggestions? I really hope you can help me! Thank you very much.
> > > 
> > > 
> > > Do you mean to identify which viewpoint is most similar to current viewpoint? Dedode is not invariant, so I think it should work, but not sure if I exactly got what you mean.
> > 
> > 
> > My requirement is to estimate the pose information of a target object through RGB images using the PnP method. I will prepare approximately ten images taken from different angles, for which I already know the object's pose information. Using DeDoDe, I will extract descriptors from these ten images and establish 2D-3D correspondences, then concatenate them. For a new image, I will extract descriptors and match them with the concatenated template. This process allows me to establish the 2D-3D relationship between the input and template images, enabling the use of PnP to solve for pose information.
> 
> Yes that should work.

Great, I will implement this part. If I encounter any issues, I'll ask for your help. Thank you!

**Comment by Parskatt** [comment]
> > > Well, it’s a very poor GPU : Nvidia T1200  CUDA version 11.4
> > 
> > What I would do is run with a debugger and find where the first nan shows up in the model forward. Perhaps pytorch has some flag to raise error when this happens?
> 
> I tried using torch.autograd.set_detect_anomaly(True), but it didn't take effect.
> ![image](https://github.com/Parskatt/DeDoDe/assets/93421835/066a8695-8e86-4d0d-9fd8-e0de18de4947)
> Here, features will change to nan
> ![image](https://github.com/Parskatt/DeDoDe/assets/93421835/31b87785-9017-4cf7-bfc4-e9af1c8219e8)
> 

Strange, the encoder should just be a vgg19. Perhaps just run with float32 and see if it works?

**Comment by GhYang0519** [comment]
> > > > Well, it’s a very poor GPU : Nvidia T1200  CUDA version 11.4
> > > 
> > > 
> > > What I would do is run with a debugger and find where the first nan shows up in the model forward. Perhaps pytorch has some flag to raise error when this happens?
> > 
> > 
> > I tried using torch.autograd.set_detect_anomaly(True), but it didn't take effect.
> > ![image](https://user-images.githubusercontent.com/93421835/281989328-066a8695-8e86-4d0d-9fd8-e0de18de4947.png)
> > Here, features will change to nan
> > ![image](https://user-images.githubusercontent.com/93421835/281989164-31b87785-9017-4cf7-bfc4-e9af1c8219e8.png)
> 
> Strange, the encoder should just be a vgg19. Perhaps just run with float32 and see if it works?

After changing to float32, everything seems to be normal!
![image](https://github.com/Parskatt/DeDoDe/assets/93421835/e822c105-c036-4549-aa0e-159720e76c45)
![image](https://github.com/Parskatt/DeDoDe/assets/93421835/d224f8bf-da73-48bb-b6c7-2b97a8f1e27c)

**Comment by GhYang0519** [comment]
> > > > Additionally, I have a question: I have multiple images of an object from different perspectives, and I obtain descriptors for each of them using DeDoDe, then concatenate them to form my template. During inference, I'm wondering if DeDoDe can still perform well when faced with this concatenated descriptor. Does the matching score still hold significance at this point? In other words, can it still identify descriptors and keypoints within this stack of descriptors that best match the current input image?
> > > > Or do you have any better suggestions? I really hope you can help me! Thank you very much.
> > > 
> > > 
> > > Do you mean to identify which viewpoint is most similar to current viewpoint? Dedode is not invariant, so I think it should work, but not sure if I exactly got what you mean.
> > 
> > 
> > My requirement is to estimate the pose information of a target object through RGB images using the PnP method. I will prepare approximately ten images taken from different angles, for which I already know the object's pose information. Using DeDoDe, I will extract descriptors from these ten images and establish 2D-3D correspondences, then concatenate them. For a new image, I will extract descriptors and match them with the concatenated template. This process allows me to establish the 2D-3D relationship between the input and template images, enabling the use of PnP to solve for pose information.
> 
> Yes that should work.

BTW, I've previously tried SuperPoint+LightGlue, but after concatenating the descriptors, the matching scores of LightGlue become unreliable. I need to set the filtering threshold very low or to 0 to get matching results. Do you have any good suggestions for my previous requirements? Is my approach feasible? Thank you very much for your response.

**Comment by Parskatt** [comment]
If its just triangulation and you use the maximum of the correlation for the concat descriptions it should work. I don't see any issue in theory at least, although havent tried myself.

**Comment by GhYang0519** [comment]
> If its just triangulation and you use the maximum of the correlation for the concat descriptions it should work. I don't see any issue in theory at least, although havent tried myself.

Great!
