### ISSUE TITLE
about ‘prep_scene_info’

### ISSUE THREAD

**Issue by wangerniuniu** [Parskatt/DeDoDe#23]
Hello, I am experiencing an issue while training DeDoDe. I am receiving the following error message: "FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/DATASET/MegaDepth/prep_scene_info/detections/detections_0275.npy'". However, the prep_scene_info folder that I downloaded does not contain a detections folder. Can you please help me understand the source of this problem?

**Comment by Parskatt** [comment]
In that script the 3D points might be missing, let me know if you face any additional issues and I can update it.

**Comment by wangerniuniu** [comment]
Thank you for your answer. May I ask where can I download undistorted MegaDepth? Currently, the Google Drive link provided by D2-Net is no longer valid. Do I have to create it myself? However, it is quite large, with over 600GB of SFM files.

**Comment by Parskatt** [comment]
Yes unfortunately.
You can do it for just a few scenes as debug to start with. 

You may be interested in looking at loftrs github issues to see if others have the same issue. There might be a solution Im not aware of.

**Comment by wangerniuniu** [comment]
Thank you for your response. Your help is greatly appreciated!
