### ISSUE TITLE
about ‘prep_scene_info’

### ISSUE THREAD

**Issue by wangerniuniu** [Parskatt/DeDoDe#24]
Hello，
When I use `dedode_descriptor-G.py` to train the descriptor network, it shows the error "FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/media/MegaDepth/prep_scene_info/detections3D/detections3D_0099.npy'", but the file generated by `prep_keypoints.py` is /home/ubuntu/media/MegaDepth/prep_scene_info/detections/detections_0099.npy. How should I solve this problem?

**Comment by Parskatt** [comment]
Yes I think there is something missing in the prep script regarding the 3D points. You can manually fix this by adding them or by just not loading them in dataloader. We found that it makes little difference between using 3D points and projecting or using the 2D detections directly.

I think I'll fix the data prep script on monday.

**Comment by Parskatt** [comment]
See https://github.com/Parskatt/DeDoDe/commit/1c03ee47949a33ffa7edc7a1db69e13f740c90ed that creates the 3D points. Should work.
