### ISSUE TITLE
getting 0 image matching correspondences for some image pair when giving whole video as consecutive image frames

### ISSUE THREAD

**Issue by Meda2997** [Parskatt/DeDoDe#4]
Hello, It was a very helpful project. I am trying to get  the camera pose from the image correspondences. but when i am giving the whole video as frames some of the frames are getting 0 or less 3 matches . So, can you please help me out.  I am using code from dome file demo_match_dedode_G.py

`if __name__ == "__main__":
    img_list = glob.glob('/home/meda/Thesis/image_data/2c7796e3-b1e9-413f-a0e8-8225ac7d586e/*.jpg')
    device = get_best_device()
    detector = dedode_detector_L(
        weights = torch.load(
            "/home/meda/Thesis/sais-master-thesis/sc_depth_pl/path_dedode/dedode_detector_L.pth"),device=device)
    descriptor = dedode_descriptor_G(
        weights = torch.load("/home/meda/Thesis/sais-master-thesis/sc_depth_pl/path_dedode/dedode_descriptor_G.pth"),device=device)
    matcher = DualSoftMaxMatcher()
    for i in range(len(img_list)-2):
        im_A_path = img_list[i]
        im_B_path = img_list[i+1]
        im_A = Image.open(im_A_path)
        im_B = Image.open(im_B_path)
        W_A, H_A = im_A.size
        W_B, H_B = im_B.size

        detections_A = detector.detect_from_path(im_A_path, num_keypoints = 10_000)
        keypoints_A, P_A = detections_A["keypoints"], detections_A["confidence"]
        detections_B = detector.detect_from_path(im_B_path, num_keypoints = 10_000)
        keypoints_B, P_B = detections_B["keypoints"], detections_B["confidence"]
        description_A = descriptor.describe_keypoints_from_path(im_A_path, keypoints_A)["descriptions"]
        description_B = descriptor.describe_keypoints_from_path(im_B_path, keypoints_B)["descriptions"]
        matches_A, matches_B, batch_ids = matcher.match(keypoints_A, description_A,
            keypoints_B, description_B,
            P_A = P_A, P_B = P_B,
            normalize = True, inv_temp=20, threshold = 0.1)#Increasing threshold -> fewer matches, fewer outliers

        matches_A, matches_B = matcher.to_pixel_coords(matches_A, matches_B, H_A, W_A, H_B, W_B)
        if matches_A.shape[0]<8 or matches_B.shape[0]< 8:   
            print('m_kpts0',matches_A.shape,'m_kpts1',matches_B.shape)
            Image.fromarray(draw_matches(im_A, matches_A[::5], im_B, matches_B[::5])).save("matches_1.jpg")
        Image.fromarray(draw_matches(im_A, matches_A[::5], im_B, matches_B[::5])).save("matches.jpg")
        `

**Comment by Parskatt** [comment]
If it's indoor it's also possible that DeDoDe performs worse, as we only train on the (mostly) outdoor dataset MegaDepth.

**Comment by Parskatt** [comment]
Closing for now, let me know if you still need help
